apiVersion: apps/v1
kind: Deployment
metadata:
  name: three-tier-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: three-tier-backend
  template:
    metadata:
      labels:
        app: three-tier-backend
    spec:
      containers:
        - name: backend
          image: sridhar145/three-tier-backend:15
          ports:
            - containerPort: 8080
